# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tinymce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='HTML Child Content')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_tinymce.TestModel')),
            ],
        ),
    ]
