# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
